# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"predict": "custom.ipynb",
         "generate": "starter.ipynb",
         "load_jsonl": "starter.ipynb",
         "render_example": "starter.ipynb",
         "render_end_example": "starter.ipynb",
         "make_prompt": "starter.ipynb"}

modules = ["custom.py",
           "starter.py"]

doc_url = "https://iyaja.github.io/ought/"

git_url = "https://github.com/iyaja/ought/tree/main/"

def custom_doc_links(name): return None
