# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate": "01_starter.ipynb",
         "load_jsonl": "01_starter.ipynb",
         "render_example": "01_starter.ipynb",
         "render_end_example": "01_starter.ipynb",
         "make_prompt": "01_starter.ipynb",
         "uniform_samples": "01_starter.ipynb",
         "Metrics": "02_metrics.ipynb",
         "EnsembleClassifier": "02_metrics.ipynb",
         "LSTMClassifier": "03_lstm.ipynb",
         "BARTClassifier": "04_bart.ipynb",
         "GPTBase": "05_gpt.ipynb",
         "GPTLMClassifier": "05_gpt.ipynb",
         "GPTMatmulClassifier": "05_gpt.ipynb",
         "GPTSimilarityClassifier": "05_gpt.ipynb"}

modules = ["starter.py",
           "metrics.py",
           "lstm.py",
           "bart.py",
           "gpt.py"]

doc_url = "https://iyaja.github.io/ought/"

git_url = "https://github.com/iyaja/ought/tree/main/"

def custom_doc_links(name): return None
