# AUTOGENERATED! DO NOT EDIT! File to edit: 04_bart.ipynb (unless otherwise specified).

__all__ = ['BARTClassifier']

# Cell
from .starter import *
from transformers import pipeline

# Cell
class BARTClassifier:
    def __init__(self, train_json_path='data/train.jsonl', samples=100, metrics=[]):
        self.clas = pipeline("zero-shot-classification", device=0)
        labels = ["AI", "Not AI"]

    def predict(self, prompt):
        pred = self.learn.predict(prompt)[0]
        return 'NOT AI' if (pred == 'False') else 'AI'