# AUTOGENERATED! DO NOT EDIT! File to edit: 04_bart.ipynb (unless otherwise specified).

__all__ = ['BARTClassifier']

# Cell
from .starter import *
from transformers import pipeline

# Cell
class BARTClassifier:
    def __init__(self, instructions='Label each of the following examples as "AI" or "NOT AI"', json='data/train.jsonl', samples=2):
        self.instructions = instructions
        self.context = uniform_samples(json, samples)
        self.clas = pipeline("zero-shot-classification", device=0)
        self.labels = ["AI", "Not AI"]

    def predict(self, prompt):
        prompt = make_prompt(self.instructions, self.context, {'text': prompt})
        # to create a concrete prediction, take the last line and strip the "LABEL: " component
        result = self.clas(prompt, self.labels)
        pred = 'Not AI' if result['scores'][0] > result['scores'][1] else 'AI'
        return pred