# AUTOGENERATED! DO NOT EDIT! File to edit: custom.ipynb (unless otherwise specified).

__all__ = ['predict']

# Cell
def predict(prompt, train_json_path="data/train.jsonl"):
    train = load_jsonl(train_json_path)
    df = pd.DataFrame(train)
    dls = TextDataLoaders.from_df(df, path=train_json_path, text_col='text', label_col='label', valid_col=None, seq_len=50)
    learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5)
    learn.fine_tune(5, 5e-2)
    pred = learn.predict(prompt)[0]
    return 'Not AI' if (pred == 'False') else 'AI'